version: '3'

services:
  db:
    image: postgres:11
    restart: always
    env_file:
      - local.envs
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
    - "6379:6379"
    expose:
    - "6379"
    volumes:
    - ../data/redis:/data
    restart: always

  backend:
    env_file:
      - local.envs
    build:
      context: ./django_gae_demo
      dockerfile: Dockerfile
    volumes:
      - ./django_gae_demo/:/code
    ports:
      - "8000:8000"
    expose:
    - "8000"
    depends_on:
      - db
      - redis
    command: python3 manage.py runserver 0.0.0.0:8000

volumes:
  data:
    external: true